### PR TITLE
V2.0.0 beta2

### LINKED ISSUE #25: android-studio studio filter only list two projects, not all of them
Q | A
--- | ---
Workflow version | _2.0.0-beta1_
OSX Version | _10.12.6 (16G29)_
Alfred Version | _v3.5 [876]_
JetBrains Product/Version | _Android Studio 2.3.3_
Installation type | _classic .dmg_

### Description

image

image

`studio` doesn't seem to find all of my projects. The two shown projects are always the same ones.

I currently have 3 projects in android-studio, but the plugin only shows two of them. I friend did the same and also has the problem, he has ~9 projects and the plugin only show two of them.

### Step to reproduce

1. Create more than two android projects
2. Install the alfred package
3. Write `studio ` and see only two projects

### PR DESCRIPTION
**Pull request by bchatard**
Add support for _match_ attribute in JSON (Alfred 3.5)
Fix #25

### CODE REVIEW

File: src/Project.php [hunk 1]
```diff
@@ -196,6 +197,15 @@ private function getProjectName($path)
             return trim(basename($path, '.sln'));
         }
 
+        if (is_readable($path . '/app/src/main/res/values/strings.xml')) {
```
Comment (GabLeRoux) [inline src/Project.php]: You should convert `$path . '/app/src/main/res/values/strings.xml'` to a variable so you can reuse it. It will make it easier to read.

File: src/Project.php [hunk 2]
```diff
@@ -22,6 +22,7 @@ class Project
 
     const XPATH_PROJECT_NAME = "(//component[@name='ProjectView']/panes/pane[@id='ProjectPane']/subPane/PATH/PATH_ELEMENT/option/@value)[1]";
     const XPATH_PROJECT_NAME_ALT = "(//component[@name='ProjectView']/panes/pane[@id='ProjectPane']/subPane/expand/path/item[contains(@type, ':ProjectViewProjectNode')]/@name)[1]";
+    const XPATH_PROJECT_NAME_AS = "//string[@name='app_name']";
```
Comment (GabLeRoux) [inline src/Project.php]: Ok I asked my teammate and his projects have a few different `app_name`. Ex: `app_name_prod`, `app_name_clientname`, `app_name_otherclientname`.

maybe grab the first `app_name` or something like that. I wonder what `android-studio` use internally to locate the name as the one in there is not the same as the one listed in the project window.

File: src/Project.php (hunk 1 above)
Comment (bchatard) [reply src/Project.php]: yes, I will and for all other case also (planned before stable release)

File: src/Project.php (hunk 2 above)
Comment (bchatard) [reply src/Project.php]: I try to find answer in test project called "My First Application", can you try too ?

```bash
→ grep "My First Application" AndroidStudioProjects/MyFirstApplication/.* -R
AndroidStudioProjects/MyFirstApplication/.idea/workspace.xml:    <ignored path="My First Application.iws" />
AndroidStudioProjects/MyFirstApplication/.idea/workspace.xml:    <favorites_list name="My First Application" />

→ grep "My First Application" AndroidStudioProjects/MyFirstApplication/* -R
AndroidStudioProjects/MyFirstApplication/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:    <string name="app_name">My First Application</string>
AndroidStudioProjects/MyFirstApplication/app/build/intermediates/incremental/mergeDebugResources/merger.xml:    </string-array><string name="pref_default_display_name">John Smith</string><string name="app_name">My First Application</string><string name="pref_description_social_recommendations">Recommendations for people to contact
AndroidStudioProjects/MyFirstApplication/app/build/intermediates/res/merged/debug/values/values.xml:    <string name="app_name">My First Application</string>
Binary file AndroidStudioProjects/MyFirstApplication/app/build/intermediates/res/resources-debug.ap_ matches
AndroidStudioProjects/MyFirstApplication/app/src/main/res/values/strings.xml:    <string name="app_name">My First Application</string>
```

Comment (bchatard) [reply src/Project.php]: mix fix doesn't works with project for multiple devices (wear, mobile etc)
```bash
→ grep "My Second Applicatiòñ" AndroidStudioProjects/* -R
AndroidStudioProjects/MySecondApplicatiòñ/.idea/workspace.xml:    <ignored path="My Second Applicatiòñ.iws" />
AndroidStudioProjects/MySecondApplicatiòñ/.idea/workspace.xml:    <favorites_list name="My Second Applicatiòñ" />
AndroidStudioProjects/MySecondApplicatiòñ/mobile/src/main/res/values/strings.xml:    <string name="app_name">My Second Applicatiòñ</string>
AndroidStudioProjects/MySecondApplicatiòñ/tv/src/main/res/values/strings.xml:    <string name="app_name">My Second Applicatiòñ</string>
AndroidStudioProjects/MySecondApplicatiòñ/wear/src/main/res/values/strings.xml:    <string name="app_name">My Second Applicatiòñ</string>
```

(yes I try wired chars too 😃 )

Comment (bchatard) [reply src/Project.php]: did you have a file `.iws` in your projects?

Comment (GabLeRoux) [reply src/Project.php]: I see this:
```bash
grep "application-cafe-jeunesse-android" . -R | grep iws
./.idea/workspace.xml:    <ignored path="application-cafe-jeunesse-android.iws" />
```

but the file is not present:
```bash
❯ find . -name "*application-cafe-jeunesse-android.iws*"
```

Could it be the `favorites_list name`? 
```
.idea/workspace.xml:    <favorites_list name="application-cafe-jeunesse-android" />
```

`favorites_list` totally sounds like android-studio's project list.

```xml
<component name="FavoritesManager">
  <favorites_list name="YOLO" />
</component>
```

I tried to edit the line, reimported project, but still showing older name so it may not be the case.

Comment (bchatard) [reply src/Project.php]: me too `.iws` doesn't exists

Favorites list can be renamed :-( 

I think this `<ignored path="My Second Applicatiòñ.iws" />` will be ok for most of the case. Can you confirm with your teammate?

For my information, did you have "old" projets - created with previous version of Android Studio?

Comment (GabLeRoux) [reply src/Project.php]: > For my information, did you have "old" projets - created with previous version of Android Studio?

Yes that's probably the case.

btw, I just tested something to find what the project name is:

image

I renamed the folder and opened it again. From the list, it uses the directory name which holds the `.idea/workspace.xml`
